sunnysmartlead/finance_back

- aspnet-core/src/Finance.Application/CustomDtoMapper.cs
- aspnet-core/src/Finance.Application/Dto/ToExamineDto.cs
- aspnet-core/src/Finance.Application/NrePricing/Dto/ProductDepartmentDto.cs
- aspnet-core/src/Finance.Application/NrePricing/Model/MouldInventoryModel.cs
- aspnet-core/src/Finance.Application/NrePricing/NrePricingAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/Dto/CreateCarModelCountDto.cs
- aspnet-core/src/Finance.Application/PriceEval/Dto/GetBomCostInput.cs
- aspnet-core/src/Finance.Application/PriceEval/Dto/GradientModelInput.cs
- aspnet-core/src/Finance.Application/PriceEval/Dto/PriceEvaluationStartInput.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationGetAppService.cs
- aspnet-core/src/Finance.Application/PropertyDepartment/DemandApplyAudit/DemandApplyAuditAppService.cs
- aspnet-core/src/Finance.Application/PropertyDepartment/Entering/Method/ElectronicStructuralMethod.cs
- aspnet-core/src/Finance.Application/WorkFlows/WorkFlowInstanceAppService.cs
- aspnet-core/src/Finance.Core/FinanceConsts.cs
- aspnet-core/src/Finance.Core/Nre/MouldInventory.cs
- aspnet-core/src/Finance.Core/PriceEval/CarModelCount.cs
- aspnet-core/src/Finance.Core/PriceEval/Gradient.cs
- aspnet-core/src/Finance.Core/PriceEval/ModelCount.cs
- aspnet-core/src/Finance.Core/WorkFlows/WorkFlow.cs
- aspnet-core/src/Finance.Core/WorkFlows/WorkFlowInstance.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/FinanceDbContext.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/DefaultFinanceDictionaryCreator.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/WorkFlowCreator.cs
- aspnet-core/test/Finance.Tests/PriceEval/PriceEvaluationAppService_Tests.cs
> Dev xyz nreem cfix

- aspnet-core/src/Finance.Application/CustomDtoMapper.cs
- aspnet-core/src/Finance.Application/TradeCompliance/CountryLibraryAppService.cs
- aspnet-core/src/Finance.Application/TradeCompliance/Dto/CountryLibraryDto.cs
- aspnet-core/src/Finance.Application/TradeCompliance/TradeComplianceAppService.cs
- aspnet-core/src/Finance.Core/TradeCompliance/CountryLibrary.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/FinanceDbContext.cs
- aspnet-core/src/Finance.EntityFrameworkCore/Finance.EntityFrameworkCore.csproj
> [ADD]贸易合规国家库

- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationGetAppService.cs
> 1、解决因退回录入界面导致的数据不唯一问题。

- aspnet-core/src/Finance.Application/TradeCompliance/TradeComplianceAppService.cs
> [ADD]贸易合规表格下载

- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/AnalyseBoardSecondAppService.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/DTo/AnalyseBoardSecondDto.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/DTo/IsOfferSecondDto.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/DTo/ProductDto.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/DTo/QuotationNreDto.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/DTo/YearDimensionalityComparisonSecondDto.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/DTo/YearProductBoardProcessSecondDto.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/IAnalyseBoardSecondAppService.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/Method/AnalysisBoardSecondMethod.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/Model/GradientQuotedGrossMarginModel.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/Model/PooledAnalysisModel.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/Model/ProjectBoardModel.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/Model/QuotedGrossMarginModel.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/Model/QuotedGrossMarginProjectModel.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/Model/SopSecondModel.cs
- aspnet-core/src/Finance.Core/MakeOffers/ProjectBoardSecondOffers.cs
- aspnet-core/src/Finance.Core/MakeOffers/SolutionQuotation.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/FinanceDbContext.cs
> Dev hwj 20231022

- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationGetAppService.cs
- aspnet-core/src/Finance.Application/WorkFlows/TradeComplianceEventHandler.cs
2、解决方案对比表部分项目不显示的问题。
3、核价看板退回到单价录入增加记录表清空动作。
> [REF] 1、修改核价看板年份排序方式。

- aspnet-core/src/Finance.Application/Audit/AuditFlowAppService.cs
- aspnet-core/src/Finance.Application/Audit/Dto/AuditFlowRightDto.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationGetAppService.cs
- aspnet-core/src/Finance.Application/WorkFlows/Dto/GetResetListInput.cs
- aspnet-core/src/Finance.Application/WorkFlows/Dto/ResetList.cs
- aspnet-core/src/Finance.Application/WorkFlows/Dto/ResetTaskInput.cs
- aspnet-core/src/Finance.Application/WorkFlows/Dto/UserTask.cs
- aspnet-core/src/Finance.Application/WorkFlows/WorkFlowInstanceAppService.cs
- aspnet-core/src/Finance.Core/WorkFlows/TaskReset.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/FinanceDbContext.cs
WorkflowInstance/GetResetList接口，获取任务重置情况列表
WorkflowInstance/ResetTask接口，把自己的任务重置给别人
> [ADD] 任务重置功能

- aspnet-core/src/Finance.Application/PriceEval/Dto/ProductionControlInfoListDto.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationGetAppService.cs
2、修改核价表分摊成本逻辑。
3、修改其他成本项计算逻辑。
4、解决核价看板全生命周期单颗成本为0的问题。
5、修改全生命周期不含客供计算逻辑。
6、修改核价表全生命周期物流费计算逻辑 。
> [REF] 1、修改物流成本计算逻辑。

- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/AnalyseBoardSecondAppService.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/DTo/IsOfferSecondDto.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/DTo/YearProductBoardProcessSecondDto.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/Method/AnalysisBoardSecondMethod.cs
- aspnet-core/src/Finance.Core/MakeOffers/DynamicUnitPriceOffers.cs
- aspnet-core/src/Finance.Core/MakeOffers/GradientGrossMarginCalculate.cs
- aspnet-core/src/Finance.Core/MakeOffers/NreQuotation.cs
- aspnet-core/src/Finance.Core/MakeOffers/SolutionQuotation.cs
- aspnet-core/src/Finance.Core/MakeOffers/UnitPriceOffers.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/FinanceDbContext.cs
> Dev hwj 1104

- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationGetAppService.cs
- aspnet-core/src/Finance.Application/WorkFlows/Dto/PanelSubmitNodeInput.cs
- aspnet-core/src/Finance.Application/WorkFlows/WorkFlowInstanceAppService.cs
2、修改制造成本显示逻辑，添加空的smt制造成本。
3、完成核价看板多界面退回后端接口。
> [REF] 1、优化核价看板的报错信息，读取NRE核价表和工时工序时如果读取不到，抛出异常。

- aspnet-core/src/Finance.Application/ProductDevelopment/ElectronicBomAppService.cs
- aspnet-core/src/Finance.Application/TradeCompliance/TradeComplianceAppService.cs
> [REF]修复电子bom七项重复容错问题

- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationGetAppService.cs
- aspnet-core/src/Finance.Application/WorkFlows/TradeComplianceEventHandler.cs
- aspnet-core/src/Finance.Core/FinanceConsts.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/DefaultFinanceDictionaryCreator.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/WorkFlowCreator.cs
2、修改是否客供计算逻辑。
3、解决贸易合规调用顺序问题。
4、核价看板退回增加退回到核价审批录入。
5、排查物流成本核价表和核价看板不一致问题。
> [REF] 1、解决提交是否客供报错问题。

- aspnet-core/src/Finance.Application/Audit/AuditFlowAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/Dto/CreateCustomerTargetPriceDto.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationGetAppService.cs
- aspnet-core/src/Finance.Core/FinanceConsts.cs
- aspnet-core/src/Finance.Core/PriceEval/CustomerTargetPrice.cs
- aspnet-core/src/Finance.Core/PriceEval/PriceEvaluationStartData.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/WorkFlowCreator.cs
2、核价需求录入增加过滤校验，项目经理和自己录入的流程才可见。
> [REF] 1、改变客户目标价参数必填，改变利润计算方法。 

- aspnet-core/src/Finance.Application/Audit/AuditFlowAppService.cs
- aspnet-core/src/Finance.Application/Audit/Dto/AuditFlowRightDto.cs
- aspnet-core/src/Finance.Application/Hr/Dto/GetUserByDeptNameInput.cs
- aspnet-core/src/Finance.Application/Hr/HrAppService.cs
- aspnet-core/src/Finance.Application/Users/Dto/PagedUserResultRequestDto.cs
- aspnet-core/src/Finance.Application/Users/UserAppService.cs
- aspnet-core/src/Finance.Application/WorkFlows/Dto/UserTask.cs
- aspnet-core/src/Finance.Application/WorkFlows/TradeComplianceEventHandler.cs
- aspnet-core/src/Finance.Application/WorkFlows/WorkFlowInstanceAppService.cs
- aspnet-core/src/Finance.Core/FinanceConsts.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/WorkFlowCreator.cs
2、解决电子结构BOM审核不能正常显示的错误。
3、解决贸易合规报错问题。
4、解决正式流程4，相关节点不能正确显示的问题。
5、增加邮件发送功能。
> [REF] 1、解决查询待办出现的错误。

- aspnet-core/src/Finance.Application/WorkFlows/LineEventHandler.cs
- aspnet-core/src/Finance.Application/WorkFlows/TradeComplianceEventHandler.cs
- aspnet-core/src/Finance.Core/FinanceConsts.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/DefaultFinanceDictionaryCreator.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/WorkFlowCreator.cs
> 1、解决从贸易不合规退回的时候，结构电子bom单价状态不能正确清空的问题。

- aspnet-core/src/Finance.Application/CustomDtoMapper.cs
- aspnet-core/src/Finance.Application/MakeOffers/AnalyseBoard/AnalyseBoardSecondAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/Dto/AfterUpdateSumDto.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/SaveAfterUpateSumAppService.cs
- aspnet-core/src/Finance.Core/Audit/FlowProcess.cs
- aspnet-core/src/Finance.Core/PriceEval/AfterUpdateSumInfo.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/FinanceDbContext.cs
> [ADD]核心器件添加核价看板修改后合计保存

- aspnet-core/src/Finance.Application/Audit/AuditFlowAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationAppService.cs
- aspnet-core/src/Finance.Application/PropertyDepartment/Entering/ResourceEnteringAppService.cs
- aspnet-core/src/Finance.Application/WorkFlows/Dto/UserTask.cs
- aspnet-core/src/Finance.Application/WorkFlows/TradeComplianceEventHandler.cs
- aspnet-core/src/Finance.Application/WorkFlows/WorkFlowInstanceAppService.cs
6、 让查看初版BOM成本、项目部长查看核价表可以直接在已办中出现。
> 5、更改贸易合规显示逻辑，可以出现在项目经理的已办之中。

- aspnet-core/src/Finance.Application/Audit/AuditFlowAppService.cs
- aspnet-core/src/Finance.Application/PropertyDepartment/Entering/ResourceEnteringAppService.cs
- aspnet-core/src/Finance.Application/VersionManagement/VersionManagmentAppService.cs
- aspnet-core/src/Finance.Application/WorkFlows/Dto/UserTask.cs
- aspnet-core/src/Finance.Application/WorkFlows/WorkFlowInstanceAppService.cs
2、解决待办重置后，在待办页面不消失的问题。
3、完成时效性页面接口。
> [REF] 1、解决部门重复问题，提交部门人员筛选相关的问题清单。

- aspnet-core/src/Finance.Application/NrePricing/Model/LaboratoryFeeModel.cs
- aspnet-core/src/Finance.Application/NrePricing/NrePricingAppService.cs
- aspnet-core/src/Finance.Application/ProductDevelopment/Dto/ProductDevelopmentInputDto.cs
- aspnet-core/src/Finance.Application/ProductDevelopment/ElectronicBomAppService.cs
- aspnet-core/src/Finance.Application/ProductDevelopment/StructionBomAppService.cs
- aspnet-core/src/Finance.Application/TradeCompliance/TradeComplianceAppService.cs
- aspnet-core/src/Finance.Core/ProductDevelopment/BomDifferent.cs
- aspnet-core/src/Finance.Core/ProductDevelopment/ElectronicBomInfo.cs
- aspnet-core/src/Finance.Core/ProductDevelopment/StructureBomInfo.cs
[ADD]增加电子BOM、结构BOM下载功能；[REF]解决贸易合规表单下载序号为123；[ADD]电子BOM上传SENSOR板部件的大小及拼版数量要必填功能添加；[ADD]EMC快速核报价
> [ADD]增加电子BOM、结构BOM下载功能；[REF]解决贸易合规表单下载序号为123；[ADD]电子BOM上传SENSOR板部件的大小及拼版数量要必填功能添加；[ADD]EMC快速核报价

- aspnet-core/src/Finance.Application/FinanceApplicationModule.cs
- aspnet-core/src/Finance.Application/PropertyDepartment/Entering/ResourceEnteringAppService.cs
- aspnet-core/src/Finance.Application/WorkFlows/TradeComplianceWorker.cs
> [REF] 1、完成贸易和规定时刷新功能。

- aspnet-core/src/Finance.Application/Audit/AuditFlowAppService.cs
- aspnet-core/src/Finance.Application/CustomDtoMapper.cs
- aspnet-core/src/Finance.Application/PriceEval/Dto/PriceEvaluationTableDto.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationGetAppService.cs
- aspnet-core/src/Finance.Core/PriceEval/BomMaterial.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/FinanceDbContext.cs
> [REF] 1、快速核报表创建

- aspnet-core/src/Finance.Application/Audit/AuditFlowAppService.cs
- aspnet-core/src/Finance.Application/VersionManagement/VersionManagmentAppService.cs
- aspnet-core/src/Finance.Application/WorkFlows/Dto/OverWorkflowInput.cs
- aspnet-core/src/Finance.Application/WorkFlows/Dto/WorkflowDeleteDto.cs
- aspnet-core/src/Finance.Application/WorkFlows/TradeComplianceEventHandler.cs
- aspnet-core/src/Finance.Application/WorkFlows/WorkFlowInstanceAppService.cs
- aspnet-core/src/Finance.Core/Authorization/Roles/StaticRoleNames.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/DefaultRolesCreator.cs
- aspnet-core/src/Finance.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/WorkFlowCreator.cs
2、解决删除流程测试时发现的问题，开发获取删除流程的接口。
3、完善新增的核价原因流转。
> [REF] 1、对接时效性页面，修复自测时发现的问题

- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationAppService.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationGetAppService.cs
- aspnet-core/src/Finance.Application/QuickQuotationReview/QuickQuotationReviewAppService.cs
- aspnet-core/src/Finance.Application/WorkFlows/WorkFlowInstanceAppService.cs
2、修改快速核报价流程防抖触发时机，解决提交失败问题。
3、添加引用流程核价看板流转excel上传校验。
> [REF] 1、核价表未上传增加异常提醒。

- aspnet-core/src/Finance.Application/PriceEval/Dto/PriceEvaluationTableDto.cs
- aspnet-core/src/Finance.Application/PriceEval/PriceEvaluationGetAppService.cs
> [REF] 1、增加结构料名称显示。

- aspnet-core/src/Finance.Application/Audit/AuditFlowAppService.cs
- aspnet-core/src/Finance.Application/Job/SendEmailJob.cs
- aspnet-core/src/Finance.Application/Job/SendEndEmailJob.cs
- aspnet-core/src/Finance.Application/Job/SendResetEmailJob.cs
- aspnet-core/src/Finance.Application/VersionManagement/VersionManagmentAppService.cs
- aspnet-core/src/Finance.Application/WorkFlows/WorkFlowInstanceAppService.cs
2、更改流程流转时发送邮件的标题，增加流程标题。
3、根据最新需求，实现流程历史接口。
> [REF] 1、解决时效性查询开始时间不正确的问题。
